[package]
name = "simple-di"
version = "0.1.1"
description = "Simple dependency injection for Rust"
authors = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }
edition = "2021"

[dependencies]
dashmap = "5"
lazy_static = "1"
